"""add cheddar mtg tables

Revision ID: 12ee6307ddd5
Revises: 213f2c7d5efb
Create Date: 2026-08-27 15:50:50.281262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12ee6307ddd5'
down_revision: Union[str, Sequence[str], None] = '213f2c7d5efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtg_card_cache',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name_key', sa.String(length=190), nullable=False),
    sa.Column('name', sa.String(length=190), nullable=False),
    sa.Column('scryfall_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('mana_cost', sa.String(length=100), nullable=True),
    sa.Column('type_line', sa.String(length=200), nullable=True),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_key')
    )
    op.create_table('mtg_deck_imports',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('lobby_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('decklist_text', sa.Text(), nullable=False),
    sa.Column('cards', sa.JSON(), nullable=False),
    sa.Column('unresolved_names', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['game_lobbies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lobby_id', 'user_id', name='uq_mtg_deck_imports_lobby_user')
    )
    op.create_table('mtg_games',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('lobby_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('lobby_started_at', sa.DateTime(), nullable=False),
    sa.Column('player1_user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('player2_user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('active_user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('untap', 'upkeep', 'draw', 'main1', 'combat_begin', 'attackers', 'blockers', 'damage', 'combat_end', 'main2', 'end', 'cleanup'), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'finished'), nullable=False),
    sa.Column('winner_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lobby_id'], ['game_lobbies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player1_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lobby_id', 'lobby_started_at', name='uq_mtg_games_lobby_session')
    )
    op.create_table('mtg_player_states',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('game_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('life', sa.Integer(), nullable=False),
    sa.Column('library', sa.JSON(), nullable=False),
    sa.Column('hand', sa.JSON(), nullable=False),
    sa.Column('battlefield', sa.JSON(), nullable=False),
    sa.Column('graveyard', sa.JSON(), nullable=False),
    sa.Column('exile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['mtg_games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'user_id', name='uq_mtg_player_states_game_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mtg_player_states')
    op.drop_table('mtg_games')
    op.drop_table('mtg_deck_imports')
    op.drop_table('mtg_card_cache')
    # ### end Alembic commands ###
