"""add perfect chain to beats scores

Revision ID: 213f2c7d5efb
Revises: bbc0c2342aa6
Create Date: 2026-08-26 14:40:13.526577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213f2c7d5efb'
down_revision: Union[str, Sequence[str], None] = 'bbc0c2342aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default only backfills existing (test) rows created before this
    # column existed — every future insert always supplies it explicitly via
    # beats.py's submit_attempt.
    op.add_column('beats_scores', sa.Column('chain', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beats_scores', 'chain')
    # ### end Alembic commands ###
