"""add chess games

Revision ID: 56a0247aaa0b
Revises: 49216abbed5c
Create Date: 2026-08-23 16:36:22.658363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56a0247aaa0b'
down_revision: Union[str, Sequence[str], None] = '49216abbed5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chess_games',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('lobby_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('lobby_started_at', sa.DateTime(), nullable=False),
    sa.Column('white_user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('black_user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('moves', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'checkmate', 'stalemate', 'draw', 'resigned'), nullable=False),
    sa.Column('winner_user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['black_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lobby_id'], ['game_lobbies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['white_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lobby_id', 'lobby_started_at', name='uq_chess_games_lobby_session')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chess_games')
    # ### end Alembic commands ###
