"""add cheddar beats tables

Revision ID: 5cac14147a32
Revises: 56a0247aaa0b
Create Date: 2026-08-25 16:50:24.506211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5cac14147a32'
down_revision: Union[str, Sequence[str], None] = '56a0247aaa0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beats_arrow_sets',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('4key', '8key'), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.JSON(), nullable=False),
    sa.Column('move_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beats_games',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('lobby_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('lobby_started_at', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.Enum('4key', '8key'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['game_lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lobby_id', 'lobby_started_at', name='uq_beats_games_lobby_session')
    )
    op.create_table('beats_scores',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('game_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('judgment', sa.Enum('miss', 'bad', 'cool', 'great', 'perfect'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['beats_games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beats_scores')
    op.drop_table('beats_games')
    op.drop_table('beats_arrow_sets')
    # ### end Alembic commands ###
