"""add chess ai support

Revision ID: a9348d2c4082
Revises: 12ee6307ddd5
Create Date: 2026-08-28 13:51:55.196768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9348d2c4082'
down_revision: Union[str, Sequence[str], None] = '12ee6307ddd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chess_games', sa.Column('ai_skill_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_bot')
    op.drop_column('chess_games', 'ai_skill_level')
    # ### end Alembic commands ###
