"""beats host-chosen bpm and pulse count

Revision ID: bbc0c2342aa6
Revises: 5cac14147a32
Create Date: 2026-08-25 17:24:45.441135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbc0c2342aa6'
down_revision: Union[str, Sequence[str], None] = '5cac14147a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beats_arrow_sets', 'bpm')
    # server_default only backfills existing (test) rows created before this
    # column existed — every future insert always supplies it explicitly via
    # beats.py's create_session, same as any other required column here.
    op.add_column('beats_games', sa.Column('bpm', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('beats_games', sa.Column('pulse_count', sa.Integer(), nullable=False, server_default='2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beats_games', 'pulse_count')
    op.drop_column('beats_games', 'bpm')
    op.add_column('beats_arrow_sets', sa.Column('bpm', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
